// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.proto.demo;

public final class PersonInfo {
  private PersonInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    String getEmail();
    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    java.util.List<Facephoto>
        getPhotoList();
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    Facephoto getPhoto(int index);
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    int getPhotoCount();
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    java.util.List<? extends FacephotoOrBuilder>
        getPhotoOrBuilderList();
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    FacephotoOrBuilder getPhotoOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code tutorial.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                photo_ = new java.util.ArrayList<Facephoto>();
                mutable_bitField0_ |= 0x00000008;
              }
              photo_.add(input.readMessage(Facephoto.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          photo_ = java.util.Collections.unmodifiableList(photo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonInfo.internal_static_tutorial_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonInfo.internal_static_tutorial_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private Object email_;
    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHOTO_FIELD_NUMBER = 4;
    private java.util.List<Facephoto> photo_;
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    public java.util.List<Facephoto> getPhotoList() {
      return photo_;
    }
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    public java.util.List<? extends FacephotoOrBuilder>
        getPhotoOrBuilderList() {
      return photo_;
    }
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    public int getPhotoCount() {
      return photo_.size();
    }
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    public Facephoto getPhoto(int index) {
      return photo_.get(index);
    }
    /**
     * <code>repeated .tutorial.Facephoto photo = 4;</code>
     */
    public FacephotoOrBuilder getPhotoOrBuilder(
        int index) {
      return photo_.get(index);
    }

    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      photo_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhotoCount(); i++) {
        if (!getPhoto(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < photo_.size(); i++) {
        output.writeMessage(4, photo_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < photo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, photo_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Person)
        PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonInfo.internal_static_tutorial_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonInfo.internal_static_tutorial_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.class, Builder.class);
      }

      // Construct using com.proto.demo.PersonInfo.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhotoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (photoBuilder_ == null) {
          photo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          photoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonInfo.internal_static_tutorial_Person_descriptor;
      }

      public Person getDefaultInstanceForType() {
        return Person.getDefaultInstance();
      }

      public Person build() {
        Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person buildPartial() {
        Person result = new Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (photoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            photo_ = java.util.Collections.unmodifiableList(photo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.photo_ = photo_;
        } else {
          result.photo_ = photoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person) {
          return mergeFrom((Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person other) {
        if (other == Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (photoBuilder_ == null) {
          if (!other.photo_.isEmpty()) {
            if (photo_.isEmpty()) {
              photo_ = other.photo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePhotoIsMutable();
              photo_.addAll(other.photo_);
            }
            onChanged();
          }
        } else {
          if (!other.photo_.isEmpty()) {
            if (photoBuilder_.isEmpty()) {
              photoBuilder_.dispose();
              photoBuilder_ = null;
              photo_ = other.photo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              photoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPhotoFieldBuilder() : null;
            } else {
              photoBuilder_.addAllMessages(other.photo_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getPhotoCount(); i++) {
          if (!getPhoto(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private Object email_ = "";
      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Facephoto> photo_ =
        java.util.Collections.emptyList();
      private void ensurePhotoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          photo_ = new java.util.ArrayList<Facephoto>(photo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Facephoto, Facephoto.Builder, FacephotoOrBuilder> photoBuilder_;

      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public java.util.List<Facephoto> getPhotoList() {
        if (photoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(photo_);
        } else {
          return photoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public int getPhotoCount() {
        if (photoBuilder_ == null) {
          return photo_.size();
        } else {
          return photoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Facephoto getPhoto(int index) {
        if (photoBuilder_ == null) {
          return photo_.get(index);
        } else {
          return photoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder setPhoto(
          int index, Facephoto value) {
        if (photoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoIsMutable();
          photo_.set(index, value);
          onChanged();
        } else {
          photoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder setPhoto(
          int index, Facephoto.Builder builderForValue) {
        if (photoBuilder_ == null) {
          ensurePhotoIsMutable();
          photo_.set(index, builderForValue.build());
          onChanged();
        } else {
          photoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder addPhoto(Facephoto value) {
        if (photoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoIsMutable();
          photo_.add(value);
          onChanged();
        } else {
          photoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder addPhoto(
          int index, Facephoto value) {
        if (photoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhotoIsMutable();
          photo_.add(index, value);
          onChanged();
        } else {
          photoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder addPhoto(
          Facephoto.Builder builderForValue) {
        if (photoBuilder_ == null) {
          ensurePhotoIsMutable();
          photo_.add(builderForValue.build());
          onChanged();
        } else {
          photoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder addPhoto(
          int index, Facephoto.Builder builderForValue) {
        if (photoBuilder_ == null) {
          ensurePhotoIsMutable();
          photo_.add(index, builderForValue.build());
          onChanged();
        } else {
          photoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder addAllPhoto(
          Iterable<? extends Facephoto> values) {
        if (photoBuilder_ == null) {
          ensurePhotoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, photo_);
          onChanged();
        } else {
          photoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder clearPhoto() {
        if (photoBuilder_ == null) {
          photo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          photoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Builder removePhoto(int index) {
        if (photoBuilder_ == null) {
          ensurePhotoIsMutable();
          photo_.remove(index);
          onChanged();
        } else {
          photoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Facephoto.Builder getPhotoBuilder(
          int index) {
        return getPhotoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public FacephotoOrBuilder getPhotoOrBuilder(
          int index) {
        if (photoBuilder_ == null) {
          return photo_.get(index);  } else {
          return photoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public java.util.List<? extends FacephotoOrBuilder>
           getPhotoOrBuilderList() {
        if (photoBuilder_ != null) {
          return photoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(photo_);
        }
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Facephoto.Builder addPhotoBuilder() {
        return getPhotoFieldBuilder().addBuilder(
            Facephoto.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public Facephoto.Builder addPhotoBuilder(
          int index) {
        return getPhotoFieldBuilder().addBuilder(
            index, Facephoto.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Facephoto photo = 4;</code>
       */
      public java.util.List<Facephoto.Builder>
           getPhotoBuilderList() {
        return getPhotoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Facephoto, Facephoto.Builder, FacephotoOrBuilder>
          getPhotoFieldBuilder() {
        if (photoBuilder_ == null) {
          photoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Facephoto, Facephoto.Builder, FacephotoOrBuilder>(
                  photo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          photo_ = null;
        }
        return photoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Person)
  }

  public interface FacephotoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Facephoto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string describe = 1;</code>
     */
    boolean hasDescribe();
    /**
     * <code>required string describe = 1;</code>
     */
    String getDescribe();
    /**
     * <code>required string describe = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescribeBytes();

    /**
     * <code>required bytes photo = 2;</code>
     */
    boolean hasPhoto();
    /**
     * <code>required bytes photo = 2;</code>
     */
    com.google.protobuf.ByteString getPhoto();
  }
  /**
   * Protobuf type {@code tutorial.Facephoto}
   */
  public static final class Facephoto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Facephoto)
      FacephotoOrBuilder {
    // Use Facephoto.newBuilder() to construct.
    private Facephoto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Facephoto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Facephoto defaultInstance;
    public static Facephoto getDefaultInstance() {
      return defaultInstance;
    }

    public Facephoto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Facephoto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              describe_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              photo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonInfo.internal_static_tutorial_Facephoto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonInfo.internal_static_tutorial_Facephoto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Facephoto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Facephoto> PARSER =
        new com.google.protobuf.AbstractParser<Facephoto>() {
      public Facephoto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Facephoto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Facephoto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DESCRIBE_FIELD_NUMBER = 1;
    private Object describe_;
    /**
     * <code>required string describe = 1;</code>
     */
    public boolean hasDescribe() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string describe = 1;</code>
     */
    public String getDescribe() {
      Object ref = describe_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          describe_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string describe = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescribeBytes() {
      Object ref = describe_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        describe_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PHOTO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString photo_;
    /**
     * <code>required bytes photo = 2;</code>
     */
    public boolean hasPhoto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes photo = 2;</code>
     */
    public com.google.protobuf.ByteString getPhoto() {
      return photo_;
    }

    private void initFields() {
      describe_ = "";
      photo_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDescribe()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhoto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDescribeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, photo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDescribeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, photo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Facephoto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Facephoto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Facephoto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Facephoto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Facephoto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Facephoto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Facephoto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Facephoto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Facephoto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Facephoto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Facephoto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Facephoto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Facephoto)
        FacephotoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PersonInfo.internal_static_tutorial_Facephoto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PersonInfo.internal_static_tutorial_Facephoto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Facephoto.class, Builder.class);
      }

      // Construct using com.proto.demo.PersonInfo.Facephoto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        describe_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        photo_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PersonInfo.internal_static_tutorial_Facephoto_descriptor;
      }

      public Facephoto getDefaultInstanceForType() {
        return Facephoto.getDefaultInstance();
      }

      public Facephoto build() {
        Facephoto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Facephoto buildPartial() {
        Facephoto result = new Facephoto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.describe_ = describe_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.photo_ = photo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Facephoto) {
          return mergeFrom((Facephoto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Facephoto other) {
        if (other == Facephoto.getDefaultInstance()) return this;
        if (other.hasDescribe()) {
          bitField0_ |= 0x00000001;
          describe_ = other.describe_;
          onChanged();
        }
        if (other.hasPhoto()) {
          setPhoto(other.getPhoto());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDescribe()) {
          
          return false;
        }
        if (!hasPhoto()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Facephoto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Facephoto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object describe_ = "";
      /**
       * <code>required string describe = 1;</code>
       */
      public boolean hasDescribe() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string describe = 1;</code>
       */
      public String getDescribe() {
        Object ref = describe_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            describe_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string describe = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescribeBytes() {
        Object ref = describe_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          describe_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string describe = 1;</code>
       */
      public Builder setDescribe(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        describe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string describe = 1;</code>
       */
      public Builder clearDescribe() {
        bitField0_ = (bitField0_ & ~0x00000001);
        describe_ = getDefaultInstance().getDescribe();
        onChanged();
        return this;
      }
      /**
       * <code>required string describe = 1;</code>
       */
      public Builder setDescribeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        describe_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString photo_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes photo = 2;</code>
       */
      public boolean hasPhoto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes photo = 2;</code>
       */
      public com.google.protobuf.ByteString getPhoto() {
        return photo_;
      }
      /**
       * <code>required bytes photo = 2;</code>
       */
      public Builder setPhoto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        photo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes photo = 2;</code>
       */
      public Builder clearPhoto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        photo_ = getDefaultInstance().getPhoto();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Facephoto)
    }

    static {
      defaultInstance = new Facephoto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Facephoto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Facephoto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Facephoto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014person.proto\022\010tutorial\"U\n\006Person\022\n\n\002id" +
      "\030\001 \002(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\"\n\005p" +
      "hoto\030\004 \003(\0132\023.tutorial.Facephoto\",\n\tFacep" +
      "hoto\022\020\n\010describe\030\001 \002(\t\022\r\n\005photo\030\002 \002(\014B\034\n" +
      "\016com.proto.demoB\nPersonInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Person_descriptor,
        new String[] { "Id", "Name", "Email", "Photo", });
    internal_static_tutorial_Facephoto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Facephoto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Facephoto_descriptor,
        new String[] { "Describe", "Photo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
