// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: result.proto

package jin.com.protobuflib.model;

public final class ResultInfo {
  private ResultInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 resultcode = 1 [default = 0];</code>
     *
     * <pre>
     * 结果吗
     * </pre>
     */
    boolean hasResultcode();
    /**
     * <code>required int64 resultcode = 1 [default = 0];</code>
     *
     * <pre>
     * 结果吗
     * </pre>
     */
    long getResultcode();

    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    boolean hasAlertMessage();
    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    java.lang.String getAlertMessage();
    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getAlertMessageBytes();

    /**
     * <code>optional int64 errorCode = 3;</code>
     *
     * <pre>
     * 错误吗
     * </pre>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int64 errorCode = 3;</code>
     *
     * <pre>
     * 错误吗
     * </pre>
     */
    long getErrorCode();

    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    boolean hasJsonInfo();
    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    java.lang.String getJsonInfo();
    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    com.google.protobuf.ByteString
        getJsonInfoBytes();
  }
  /**
   * Protobuf type {@code tutorial.Result}
   */
  public static final class Result extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }

    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultcode_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              alertMessage_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errorCode_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              errorMessage_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              jsonInfo_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jin.com.protobuflib.model.ResultInfo.internal_static_tutorial_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jin.com.protobuflib.model.ResultInfo.internal_static_tutorial_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jin.com.protobuflib.model.ResultInfo.Result.class, jin.com.protobuflib.model.ResultInfo.Result.Builder.class);
    }

    public static com.google.protobuf.Parser<Result> PARSER =
        new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private long resultcode_;
    /**
     * <code>required int64 resultcode = 1 [default = 0];</code>
     *
     * <pre>
     * 结果吗
     * </pre>
     */
    public boolean hasResultcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 resultcode = 1 [default = 0];</code>
     *
     * <pre>
     * 结果吗
     * </pre>
     */
    public long getResultcode() {
      return resultcode_;
    }

    public static final int ALERTMESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object alertMessage_;
    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    public boolean hasAlertMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    public java.lang.String getAlertMessage() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          alertMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string alertMessage = 2;</code>
     *
     * <pre>
     * 提示信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAlertMessageBytes() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private long errorCode_;
    /**
     * <code>optional int64 errorCode = 3;</code>
     *
     * <pre>
     * 错误吗
     * </pre>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 errorCode = 3;</code>
     *
     * <pre>
     * 错误吗
     * </pre>
     */
    public long getErrorCode() {
      return errorCode_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 4;
    private java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 4;</code>
     *
     * <pre>
     * 错误信息提示
     * </pre>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JSONINFO_FIELD_NUMBER = 5;
    private java.lang.Object jsonInfo_;
    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    public boolean hasJsonInfo() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    public java.lang.String getJsonInfo() {
      java.lang.Object ref = jsonInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string jsonInfo = 5;</code>
     *
     * <pre>
     * 返回的结果信息,
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJsonInfoBytes() {
      java.lang.Object ref = jsonInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultcode_ = 0L;
      alertMessage_ = "";
      errorCode_ = 0L;
      errorMessage_ = "";
      jsonInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasResultcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, resultcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAlertMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, errorCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getJsonInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, resultcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAlertMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, errorCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getJsonInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jin.com.protobuflib.model.ResultInfo.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jin.com.protobuflib.model.ResultInfo.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Result)
        jin.com.protobuflib.model.ResultInfo.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jin.com.protobuflib.model.ResultInfo.internal_static_tutorial_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jin.com.protobuflib.model.ResultInfo.internal_static_tutorial_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jin.com.protobuflib.model.ResultInfo.Result.class, jin.com.protobuflib.model.ResultInfo.Result.Builder.class);
      }

      // Construct using jin.com.protobuflib.model.ResultInfo.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultcode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        alertMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        jsonInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jin.com.protobuflib.model.ResultInfo.internal_static_tutorial_Result_descriptor;
      }

      public jin.com.protobuflib.model.ResultInfo.Result getDefaultInstanceForType() {
        return jin.com.protobuflib.model.ResultInfo.Result.getDefaultInstance();
      }

      public jin.com.protobuflib.model.ResultInfo.Result build() {
        jin.com.protobuflib.model.ResultInfo.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jin.com.protobuflib.model.ResultInfo.Result buildPartial() {
        jin.com.protobuflib.model.ResultInfo.Result result = new jin.com.protobuflib.model.ResultInfo.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultcode_ = resultcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.alertMessage_ = alertMessage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.jsonInfo_ = jsonInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jin.com.protobuflib.model.ResultInfo.Result) {
          return mergeFrom((jin.com.protobuflib.model.ResultInfo.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jin.com.protobuflib.model.ResultInfo.Result other) {
        if (other == jin.com.protobuflib.model.ResultInfo.Result.getDefaultInstance()) return this;
        if (other.hasResultcode()) {
          setResultcode(other.getResultcode());
        }
        if (other.hasAlertMessage()) {
          bitField0_ |= 0x00000002;
          alertMessage_ = other.alertMessage_;
          onChanged();
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000008;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (other.hasJsonInfo()) {
          bitField0_ |= 0x00000010;
          jsonInfo_ = other.jsonInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultcode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jin.com.protobuflib.model.ResultInfo.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jin.com.protobuflib.model.ResultInfo.Result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long resultcode_ ;
      /**
       * <code>required int64 resultcode = 1 [default = 0];</code>
       *
       * <pre>
       * 结果吗
       * </pre>
       */
      public boolean hasResultcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 resultcode = 1 [default = 0];</code>
       *
       * <pre>
       * 结果吗
       * </pre>
       */
      public long getResultcode() {
        return resultcode_;
      }
      /**
       * <code>required int64 resultcode = 1 [default = 0];</code>
       *
       * <pre>
       * 结果吗
       * </pre>
       */
      public Builder setResultcode(long value) {
        bitField0_ |= 0x00000001;
        resultcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 resultcode = 1 [default = 0];</code>
       *
       * <pre>
       * 结果吗
       * </pre>
       */
      public Builder clearResultcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultcode_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object alertMessage_ = "";
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public boolean hasAlertMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public java.lang.String getAlertMessage() {
        java.lang.Object ref = alertMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            alertMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAlertMessageBytes() {
        java.lang.Object ref = alertMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alertMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public Builder setAlertMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alertMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public Builder clearAlertMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        alertMessage_ = getDefaultInstance().getAlertMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string alertMessage = 2;</code>
       *
       * <pre>
       * 提示信息
       * </pre>
       */
      public Builder setAlertMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        alertMessage_ = value;
        onChanged();
        return this;
      }

      private long errorCode_ ;
      /**
       * <code>optional int64 errorCode = 3;</code>
       *
       * <pre>
       * 错误吗
       * </pre>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 errorCode = 3;</code>
       *
       * <pre>
       * 错误吗
       * </pre>
       */
      public long getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int64 errorCode = 3;</code>
       *
       * <pre>
       * 错误吗
       * </pre>
       */
      public Builder setErrorCode(long value) {
        bitField0_ |= 0x00000004;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 errorCode = 3;</code>
       *
       * <pre>
       * 错误吗
       * </pre>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 4;</code>
       *
       * <pre>
       * 错误信息提示
       * </pre>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jsonInfo_ = "";
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public boolean hasJsonInfo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public java.lang.String getJsonInfo() {
        java.lang.Object ref = jsonInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public com.google.protobuf.ByteString
          getJsonInfoBytes() {
        java.lang.Object ref = jsonInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public Builder setJsonInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        jsonInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public Builder clearJsonInfo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jsonInfo_ = getDefaultInstance().getJsonInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string jsonInfo = 5;</code>
       *
       * <pre>
       * 返回的结果信息,
       * </pre>
       */
      public Builder setJsonInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        jsonInfo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Result)
    }

    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Result)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014result.proto\022\010tutorial\"p\n\006Result\022\025\n\nre" +
      "sultcode\030\001 \002(\003:\0010\022\024\n\014alertMessage\030\002 \001(\t\022" +
      "\021\n\terrorCode\030\003 \001(\003\022\024\n\014errorMessage\030\004 \001(\t" +
      "\022\020\n\010jsonInfo\030\005 \001(\tB\'\n\031jin.com.protobufli" +
      "b.modelB\nResultInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Result_descriptor,
        new java.lang.String[] { "Resultcode", "AlertMessage", "ErrorCode", "ErrorMessage", "JsonInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
